[workspace]

members = [
    "day_01_1",
    "day_01_2",
    "day_02_1",
    "day_02_2",
    "day_03_1",
    "day_03_2",
    "day_04_1",
    "day_04_2",
    "day_05_1",
    "day_05_2",
    "day_06_1",
    "day_06_2",
]
